feat: fix install docker in ci

diff --git a/.github/workflows/deploy-api.yml b/.github/workflows/deploy-api.yml
--- a/.github/workflows/deploy-api.yml
+++ b/.github/workflows/deploy-api.yml
@@ -69,6 +69,19 @@ jobs:
               echo "rsync is already installed."
             fi
 
+            if ! docker --version &> /dev/null
+            then
+              echo "Docker could not be found or is not working, installing..."
+              sudo apt-get update
+              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
+              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+              sudo apt-get update
+              sudo apt-get install -y docker-ce
+            else
+              echo "Docker is already installed and working."
+            fi
+
             if ! docker-compose --version &> /dev/null
             then
               echo "docker-compose could not be found or is not working, installing..."
